# Generated by Django 5.2.7 on 2026-06-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_page_queue_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='Profile-scoped structured note from the latest review action'),
        ),
        migrations.AddField(
            model_name='page',
            name='review_outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('skipped', 'Skipped'), ('stale', 'Stale'), ('needs_follow_up', 'Needs follow-up')], default='pending', help_text='Structured review outcome for API and agent workflows', max_length=32),
        ),
        migrations.AddField(
            model_name='page',
            name='review_outcome_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemap',
            name='import_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='Latest sitemap import or refresh status', max_length=20),
        ),
        migrations.AddField(
            model_name='sitemap',
            name='last_import_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemap',
            name='last_import_message',
            field=models.TextField(blank=True, default='', help_text='Safe summary of the latest sitemap import or refresh outcome'),
        ),
        migrations.AddField(
            model_name='sitemap',
            name='last_import_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
